### ISSUE TITLE
Hackday TODO Items

### ISSUE THREAD

**Issue by blahmonkey** [eka-foundation/jelpi#7]
### List of TODOs for the hackday

**Comment by blahmonkey** [comment]
FB messenger to connect 2 users -- https://www.reddit.com/r/tasker/comments/5nmgu9/open_facebook_messenger_chathead_directly/

Needs to be tested

**Comment by blahmonkey** [comment]
Steps to run the app:

1. Copy .env.example to .env
2. Edit .env and add `APP_KEY=somelongstringthatisuspersafeandnoonecan`
3. Run `npm install`
4. Run `node server.js`

**Comment by blahmonkey** [comment]
HTML5 geolocation API specifics
https://www.w3schools.com/html/html5_geolocation.asp

**Comment by MrHakala** [comment]
Can't edit initial issue so continuing here:
 - [ ] UI - 'Can Help' page layout: request type filtering (by Vartiainen)
 - [x] SQLite DB setup by MrHakala
 - [ ] REST API Handlers by MrHakala (_need to improve barebones setup_)
 - [ ] Backend - take settings from config file by McSneaky (_unsure what this involves_)
 - [ ] UI - 'Need help' page disclaimer + FB Auth design
 - [x] UI - 'Need help' page geolocation by Vartiainen
 - [ ] UI - 'Need help' page FB auth implementation
 - [x] UI - 'Need help' page javascript + xhr request
 - [ ] UI - ~~'Can help' page FB auth~~ (not needed using `https://m.me/FB_ID`-link ?)
 - [ ] UI - 'Can Help' page javascript + xhr request
 - [ ] UI - Take all language strings from configuration file
 - [ ] UI - Take all configurable style from configuration file
(_also_)
 - [ ] UI & Backend - make option for user to delete their request (then need FB auth?)
 - [ ] Privacy - delete requests older than 24-48h
...
 - [ ] Backend - move (initial) geolocation filtering to backend
 - [ ] Backend - move type filering to backend
